package top.maweihao.weather.entity.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEW_HE_WEATHER_NOW".
*/
public class NewHeWeatherNowDao extends AbstractDao<NewHeWeatherNow, Long> {

    public static final String TABLENAME = "NEW_HE_WEATHER_NOW";

    /**
     * Properties of entity NewHeWeatherNow.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CurrentTimeInMills = new Property(0, long.class, "currentTimeInMills", true, "_id");
        public final static Property JsonString = new Property(1, String.class, "jsonString", false, "JSON_STRING");
    }


    public NewHeWeatherNowDao(DaoConfig config) {
        super(config);
    }
    
    public NewHeWeatherNowDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEW_HE_WEATHER_NOW\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: currentTimeInMills
                "\"JSON_STRING\" TEXT);"); // 1: jsonString
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEW_HE_WEATHER_NOW\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NewHeWeatherNow entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCurrentTimeInMills());
 
        String jsonString = entity.getJsonString();
        if (jsonString != null) {
            stmt.bindString(2, jsonString);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NewHeWeatherNow entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCurrentTimeInMills());
 
        String jsonString = entity.getJsonString();
        if (jsonString != null) {
            stmt.bindString(2, jsonString);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public NewHeWeatherNow readEntity(Cursor cursor, int offset) {
        NewHeWeatherNow entity = new NewHeWeatherNow( //
            cursor.getLong(offset + 0), // currentTimeInMills
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // jsonString
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NewHeWeatherNow entity, int offset) {
        entity.setCurrentTimeInMills(cursor.getLong(offset + 0));
        entity.setJsonString(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NewHeWeatherNow entity, long rowId) {
        entity.setCurrentTimeInMills(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NewHeWeatherNow entity) {
        if(entity != null) {
            return entity.getCurrentTimeInMills();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NewHeWeatherNow entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
