package top.maweihao.weather.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEW_WEATHER_REALTIME".
*/
public class NewWeatherRealtimeDao extends AbstractDao<NewWeatherRealtime, Long> {

    public static final String TABLENAME = "NEW_WEATHER_REALTIME";

    /**
     * Properties of entity NewWeatherRealtime.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Server_time = new Property(0, long.class, "server_time", true, "_id");
        public final static Property JsonString = new Property(1, String.class, "jsonString", false, "JSON_STRING");
    }


    public NewWeatherRealtimeDao(DaoConfig config) {
        super(config);
    }
    
    public NewWeatherRealtimeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEW_WEATHER_REALTIME\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: server_time
                "\"JSON_STRING\" TEXT);"); // 1: jsonString
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEW_WEATHER_REALTIME\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NewWeatherRealtime entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getServer_time());
 
        String jsonString = entity.getJsonString();
        if (jsonString != null) {
            stmt.bindString(2, jsonString);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NewWeatherRealtime entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getServer_time());
 
        String jsonString = entity.getJsonString();
        if (jsonString != null) {
            stmt.bindString(2, jsonString);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public NewWeatherRealtime readEntity(Cursor cursor, int offset) {
        NewWeatherRealtime entity = new NewWeatherRealtime( //
            cursor.getLong(offset + 0), // server_time
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // jsonString
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NewWeatherRealtime entity, int offset) {
        entity.setServer_time(cursor.getLong(offset + 0));
        entity.setJsonString(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(NewWeatherRealtime entity, long rowId) {
        entity.setServer_time(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(NewWeatherRealtime entity) {
        if(entity != null) {
            return entity.getServer_time();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NewWeatherRealtime entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
